/*VOLVER TODO A CERO, BORRAR BASE DE DATOS Y USUARIO (SE DEBERÍA EJECUTAR COMO ROOT)*/
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'students_user'@'localhost';
DROP USER IF EXISTS 'students_user'@'localhost';
DROP DATABASE IF EXISTS students_db;